import Head from "next/head";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>My Demo App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div>HEllo Friends</div>
    </>
  );
}
